import type { IRawNameEntry, ISourceResult } from "../types";

const SOURCE_NAME = "wikipedia-surname";

const LIST_SURNAME_FREQUENCY: Array<{ value: string; weight: number }> = [
  { value: "Nguyễn", weight: 31.5 },
  { value: "Trần", weight: 10.9 },
  { value: "Lê", weight: 8.9 },
  { value: "Phạm", weight: 5.9 },
  { value: "Hoàng", weight: 5.1 },
  { value: "Vũ", weight: 4.9 },
  { value: "Phan", weight: 2.8 },
  { value: "Trương", weight: 2.2 },
  { value: "Bùi", weight: 2.1 },
  { value: "Đỗ", weight: 1.9 },
  { value: "Đặng", weight: 1.9 },
  { value: "Ngô", weight: 1.7 },
  { value: "Hồ", weight: 1.5 },
  { value: "Dương", weight: 1.4 },
  { value: "Lý", weight: 1.0 },
  { value: "Hà", weight: 1.2 },
  { value: "Trịnh", weight: 1.0 },
  { value: "Đinh", weight: 0.9 },
  { value: "Đoàn", weight: 0.7 },
  { value: "Cao", weight: 0.7 },
  { value: "Lương", weight: 0.7 },
  { value: "Lâm", weight: 0.7 },
  { value: "Đào", weight: 0.6 },
  { value: "Mai", weight: 0.6 },
  { value: "Lưu", weight: 0.6 },
  { value: "Thái", weight: 0.5 },
  { value: "Phùng", weight: 0.4 },
  { value: "Chu", weight: 0.4 },
  { value: "Tạ", weight: 0.4 },
  { value: "Vương", weight: 0.4 },
];

const LIST_SURNAME_EXTENDED: string[] = [
  "Ái",
  "An",
  "Âu",
  "Bạch",
  "Bàn",
  "Bảo",
  "Bế",
  "Biện",
  "Bồ",
  "Ca",
  "Cầm",
  "Cảnh",
  "Châu",
  "Chế",
  "Chiêm",
  "Chính",
  "Cổ",
  "Cù",
  "Cung",
  "Đậu",
  "Di",
  "Dịch",
  "Du",
  "Đức",
  "Dung",
  "Gia",
  "Giang",
  "Hám",
  "Hàn",
  "Hầu",
  "Hiền",
  "Hòa",
  "Học",
  "Hồng",
  "Huế",
  "Hưng",
  "Hướng",
  "Kế",
  "Kha",
  "Khâm",
  "Khấu",
  "Khổng",
  "Khúc",
  "Kiều",
  "Kim",
  "La",
  "Lạc",
  "Lại",
  "Lãng",
  "Lãnh",
  "Liễu",
  "Linh",
  "Lô",
  "Lộc",
  "Long",
  "Lư",
  "Lục",
  "Lùng",
  "Mã",
  "Mạc",
  "Mạn",
  "Mang",
  "Mâu",
  "Mi",
  "Miêu",
  "Mục",
  "Na",
  "Nhâm",
  "Nhẫn",
  "Nhiệm",
  "Như",
  "Ninh",
  "Nông",
  "Nữ",
  "Ông",
  "Phác",
  "Phi",
  "Phó",
  "Phú",
  "Phúc",
  "Phước",
  "Phương",
  "Quách",
  "Quản",
  "Quang",
  "Quyền",
  "Sầm",
  "Sơn",
  "Sử",
  "Sung",
  "Tải",
  "Tăng",
  "Tào",
  "Tập",
  "Thạch",
  "Thăng",
  "Thành",
  "Thào",
  "Thi",
  "Thiên",
  "Thịnh",
  "Thọ",
  "Thôi",
  "Thư",
  "Thục",
  "Tiên",
  "Tô",
  "Tống",
  "Trầm",
  "Trí",
  "Triệu",
  "Trọng",
  "Tú",
  "Túc",
  "Tùng",
  "Tưởng",
  "Tửu",
  "Uông",
  "Văn",
  "Vi",
  "Viên",
  "Vĩnh",
  "Xa",
  "Xuân",
  "Yên",
];

export async function sourceWikipediaSurnameCrawl(): Promise<ISourceResult> {
  const entries: IRawNameEntry[] = [];

  for (let i = 0; i < LIST_SURNAME_FREQUENCY.length; i += 1) {
    entries.push({
      value: LIST_SURNAME_FREQUENCY[i].value,
      type: "surname",
      source: SOURCE_NAME,
      frequency: LIST_SURNAME_FREQUENCY[i].weight,
    });
  }

  for (let i = 0; i < LIST_SURNAME_EXTENDED.length; i += 1) {
    entries.push({
      value: LIST_SURNAME_EXTENDED[i],
      type: "surname",
      source: SOURCE_NAME,
      frequency: 0.05,
    });
  }

  entries.push({
    value: "Huỳnh",
    type: "surname",
    source: SOURCE_NAME,
    frequency: 5.1,
    region: "south",
  });
  entries.push({
    value: "Võ",
    type: "surname",
    source: SOURCE_NAME,
    frequency: 4.9,
    region: "south",
  });

  return { sourceName: SOURCE_NAME, entries, errors: [] };
}
