import * as fs from "node:fs";
import * as path from "node:path";
import type { IRawNameEntry } from "../types";
import compoundGivenNamesData from "../enrichment/compound-given-names.json";
import compoundSurnamesData from "../enrichment/compound-surnames.json";
import ethnicSurnamesData from "../enrichment/ethnic-surnames.json";
import middleNamesData from "../enrichment/middle-names.json";
import regionTagsData from "../enrichment/region-tags.json";

type TRegion = "north" | "central" | "south";
type TEra = "traditional" | "modern";
type TGender = "male" | "female" | "unisex";

const REGIONS: TRegion[] = ["north", "central", "south"];
const ERAS: TEra[] = ["traditional", "modern"];
const GENDERS: TGender[] = ["male", "female", "unisex"];

// Surnames that are regional variants — exclude from opposite regions
const SOUTH_ONLY_SURNAMES = new Set(["Huỳnh", "Võ"]);
const NORTH_CENTRAL_ONLY_SURNAMES = new Set(["Hoàng", "Vũ"]);

function regionExclude(value: string, region: TRegion): boolean {
  if (region === "south" && NORTH_CENTRAL_ONLY_SURNAMES.has(value)) {
    return true;
  }
  if (
    (region === "north" || region === "central") &&
    SOUTH_ONLY_SURNAMES.has(value)
  ) {
    return true;
  }
  return false;
}

// ─── Surname Export ──────────────────────────────────────────────────────────

function surnameExport(entries: IRawNameEntry[]): string {
  const surnameEntries = entries.filter((e) => e.type === "surname");

  // Build per-region weighted arrays from crawled data
  const regionMap: Record<TRegion, Map<string, number>> = {
    north: new Map(),
    central: new Map(),
    south: new Map(),
  };

  for (let i = 0; i < surnameEntries.length; i += 1) {
    const entry = surnameEntries[i];
    const weight = entry.frequency ?? 1;

    if (entry.region) {
      // Region-specific entry
      if (!regionExclude(entry.value, entry.region)) {
        const existing = regionMap[entry.region].get(entry.value) ?? 0;
        regionMap[entry.region].set(entry.value, Math.max(existing, weight));
      }
    } else {
      // Universal — add to all regions unless excluded
      for (let r = 0; r < REGIONS.length; r += 1) {
        const region = REGIONS[r];
        if (!regionExclude(entry.value, region)) {
          const existing = regionMap[region].get(entry.value) ?? 0;
          regionMap[region].set(entry.value, Math.max(existing, weight));
        }
      }
    }
  }

  // Add compound surnames with weight 0.01
  const compoundSurnames = compoundSurnamesData as Array<{
    value: string;
    gender?: string;
    note?: string;
  }>;
  for (let i = 0; i < compoundSurnames.length; i += 1) {
    const cs = compoundSurnames[i];
    for (let r = 0; r < REGIONS.length; r += 1) {
      const region = REGIONS[r];
      if (!regionMap[region].has(cs.value)) {
        regionMap[region].set(cs.value, 0.01);
      }
    }
  }

  // Add ethnic surnames with weight 0.02
  const ethnicGroups = ethnicSurnamesData as Record<string, string[]>;
  for (const groupNames of Object.values(ethnicGroups)) {
    for (let i = 0; i < groupNames.length; i += 1) {
      const name = groupNames[i];
      for (let r = 0; r < REGIONS.length; r += 1) {
        const region = REGIONS[r];
        if (!regionMap[region].has(name)) {
          regionMap[region].set(name, 0.02);
        }
      }
    }
  }

  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by crawl pipeline -- do not edit manually");
  lines.push('import type { TWeightedEntry } from "../types";');
  lines.push("");
  lines.push(
    "export const INDEX_SURNAME: Record<string, TWeightedEntry[]> = {",
  );

  for (let r = 0; r < REGIONS.length; r += 1) {
    const region = REGIONS[r];
    const entries = Array.from(regionMap[region].entries()).sort(
      (a, b) => b[1] - a[1],
    );

    lines.push(`  "${region}": [`);
    for (let i = 0; i < entries.length; i += 1) {
      const [value, weight] = entries[i];
      const comma = i < entries.length - 1 ? "," : "";
      lines.push(
        `    { value: ${JSON.stringify(value)}, weight: ${weight} }${comma}`,
      );
    }
    const regionComma = r < REGIONS.length - 1 ? "," : "";
    lines.push(`  ]${regionComma}`);
  }

  lines.push("};");
  lines.push("");

  return lines.join("\n");
}

// ─── Middle Name Export ───────────────────────────────────────────────────────

function middleNameExport(): string {
  type TMiddleNameData = Record<
    string,
    Record<string, Record<string, string[]>>
  >;
  const data = middleNamesData as TMiddleNameData;

  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by crawl pipeline -- do not edit manually");
  lines.push("");
  lines.push(
    "export const INDEX_MIDDLE_NAME: Record<string, Record<string, Record<string, string[]>>> = {",
  );

  for (let g = 0; g < GENDERS.length; g += 1) {
    const gender = GENDERS[g];
    const genderData = data[gender];
    const genderComma = g < GENDERS.length - 1 ? "," : "";

    lines.push(`  "${gender}": {`);

    for (let r = 0; r < REGIONS.length; r += 1) {
      const region = REGIONS[r];
      const regionComma = r < REGIONS.length - 1 ? "," : "";

      lines.push(`    "${region}": {`);

      for (let e = 0; e < ERAS.length; e += 1) {
        const era = ERAS[e];
        const eraComma = e < ERAS.length - 1 ? "," : "";

        // Use region-specific array, fall back to "all"
        const eraData = genderData[era] as Record<string, string[]>;
        const names: string[] = eraData[region] ?? eraData["all"] ?? [];

        lines.push(`      "${era}": ${JSON.stringify(names)}${eraComma}`);
      }

      lines.push(`    }${regionComma}`);
    }

    lines.push(`  }${genderComma}`);
  }

  lines.push("};");
  lines.push("");

  return lines.join("\n");
}

// ─── Given Name Export ────────────────────────────────────────────────────────

type TGivenNameCell = Array<{
  value: string;
  meaning?: string;
  sinoVietnamese?: string;
  category?: string;
}>;

function givenNameExport(entries: IRawNameEntry[]): string {
  const givenNameEntries = entries.filter((e) => e.type === "givenName");

  // Build: gender -> region -> era -> Set<value> for dedup, and metadata map
  const index: Record<
    TGender,
    Record<
      TRegion,
      Record<
        TEra,
        Map<
          string,
          { meaning?: string; sinoVietnamese?: string; category?: string }
        >
      >
    >
  > = {
    male: {
      north: { traditional: new Map(), modern: new Map() },
      central: { traditional: new Map(), modern: new Map() },
      south: { traditional: new Map(), modern: new Map() },
    },
    female: {
      north: { traditional: new Map(), modern: new Map() },
      central: { traditional: new Map(), modern: new Map() },
      south: { traditional: new Map(), modern: new Map() },
    },
    unisex: {
      north: { traditional: new Map(), modern: new Map() },
      central: { traditional: new Map(), modern: new Map() },
      south: { traditional: new Map(), modern: new Map() },
    },
  };

  for (let i = 0; i < givenNameEntries.length; i += 1) {
    const entry = givenNameEntries[i];
    const meta = {
      meaning: entry.meaning,
      sinoVietnamese: entry.sinoVietnamese,
      category: entry.category,
    };

    const genders: TGender[] = entry.gender
      ? [entry.gender]
      : ["male", "female", "unisex"];
    const regions: TRegion[] = entry.region
      ? [entry.region]
      : ["north", "central", "south"];
    const eras: TEra[] = entry.era ? [entry.era] : ["traditional", "modern"];

    for (let gi = 0; gi < genders.length; gi += 1) {
      const gender = genders[gi];
      for (let ri = 0; ri < regions.length; ri += 1) {
        const region = regions[ri];
        for (let ei = 0; ei < eras.length; ei += 1) {
          const era = eras[ei];
          const cell = index[gender][region][era];
          if (!cell.has(entry.value)) {
            cell.set(entry.value, meta);
          }
        }
      }
    }
  }

  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by crawl pipeline -- do not edit manually");
  lines.push('import type { TGivenNameEntry } from "../types";');
  lines.push("");
  lines.push(
    "export const INDEX_GIVEN_NAME: Record<string, Record<string, Record<string, TGivenNameEntry[]>>> = {",
  );

  for (let g = 0; g < GENDERS.length; g += 1) {
    const gender = GENDERS[g];
    const genderComma = g < GENDERS.length - 1 ? "," : "";

    lines.push(`  "${gender}": {`);

    for (let r = 0; r < REGIONS.length; r += 1) {
      const region = REGIONS[r];
      const regionComma = r < REGIONS.length - 1 ? "," : "";

      lines.push(`    "${region}": {`);

      for (let e = 0; e < ERAS.length; e += 1) {
        const era = ERAS[e];
        const eraComma = e < ERAS.length - 1 ? "," : "";

        const cell = index[gender][region][era];
        const cellEntries = Array.from(cell.entries());

        if (cellEntries.length === 0) {
          lines.push(`      "${era}": []${eraComma}`);
        } else {
          lines.push(`      "${era}": [`);
          for (let ci = 0; ci < cellEntries.length; ci += 1) {
            const [value, meta] = cellEntries[ci];
            const entryComma = ci < cellEntries.length - 1 ? "," : "";
            const parts: string[] = [`value: ${JSON.stringify(value)}`];
            if (meta.meaning) {
              parts.push(`meaning: ${JSON.stringify(meta.meaning)}`);
            }
            if (meta.sinoVietnamese) {
              parts.push(
                `sinoVietnamese: ${JSON.stringify(meta.sinoVietnamese)}`,
              );
            }
            if (meta.category) {
              parts.push(`category: ${JSON.stringify(meta.category)}`);
            }
            lines.push(`        { ${parts.join(", ")} }${entryComma}`);
          }
          lines.push(`      ]${eraComma}`);
        }
      }

      lines.push(`    }${regionComma}`);
    }

    lines.push(`  }${genderComma}`);
  }

  lines.push("};");
  lines.push("");

  return lines.join("\n");
}

// ─── Compound Given Name Export ───────────────────────────────────────────────

function compoundGivenNameExport(): string {
  type TCompoundData = Record<string, Record<string, string[]>>;
  const data = compoundGivenNamesData as TCompoundData;

  const lines: string[] = [];
  lines.push("// AUTO-GENERATED by crawl pipeline -- do not edit manually");
  lines.push("");
  lines.push(
    "export const INDEX_COMPOUND_GIVEN_NAME: Record<string, Record<string, string[]>> = {",
  );

  for (let g = 0; g < GENDERS.length; g += 1) {
    const gender = GENDERS[g];
    const genderComma = g < GENDERS.length - 1 ? "," : "";
    const genderData = data[gender] ?? {};

    lines.push(`  "${gender}": {`);

    for (let e = 0; e < ERAS.length; e += 1) {
      const era = ERAS[e];
      const eraComma = e < ERAS.length - 1 ? "," : "";
      const names: string[] = genderData[era] ?? [];

      lines.push(`    "${era}": ${JSON.stringify(names)}${eraComma}`);
    }

    lines.push(`  }${genderComma}`);
  }

  lines.push("};");
  lines.push("");

  return lines.join("\n");
}

// ─── Main Export Function ─────────────────────────────────────────────────────

export function entriesExport(entries: IRawNameEntry[]): void {
  const dataDir = path.resolve(import.meta.dirname, "../../../src/data");

  // Verify region-tags data is loaded (used for variant logic)
  const _regionTags = regionTagsData;
  void _regionTags;

  const files: Array<{ name: string; content: string }> = [
    { name: "surname.ts", content: surnameExport(entries) },
    { name: "middle-name.ts", content: middleNameExport() },
    { name: "given-name.ts", content: givenNameExport(entries) },
    { name: "compound-given-name.ts", content: compoundGivenNameExport() },
  ];

  for (let i = 0; i < files.length; i += 1) {
    const file = files[i];
    const filePath = path.join(dataDir, file.name);
    fs.writeFileSync(filePath, file.content, "utf-8");
    console.log(`[export] Written: ${filePath}`);
  }

  console.log(`[export] Done — ${files.length} files written to ${dataDir}`);
}
