/**
 * Converts given-name.ts from verbose object-per-entry format
 * to compact pipe-delimited strings + separate category map.
 *
 * Run: npx tsx scripts/compact-data.ts
 */

import { INDEX_GIVEN_NAME } from "../src/data/given-name";

const raw: Record<string, Record<string, Record<string, string>>> = {};
const categories: Record<string, string> = {};

for (const [gender, regions] of Object.entries(INDEX_GIVEN_NAME)) {
  raw[gender] = {};
  for (const [region, eras] of Object.entries(regions)) {
    raw[gender][region] = {};
    for (const [era, entries] of Object.entries(eras)) {
      raw[gender][region][era] = entries.map((e) => e.value).join("|");
      for (const entry of entries) {
        if (entry.category) {
          categories[entry.value] = entry.category;
        }
      }
    }
  }
}

// Generate the compact data file
const lines: string[] = [];
lines.push(
  "// AUTO-GENERATED by scripts/compact-data.ts -- do not edit manually",
);
lines.push("");
lines.push(
  "const R: Record<string, Record<string, Record<string, string>>> = ",
);
lines.push(JSON.stringify(raw, null, 0) + ";");
lines.push("");

if (Object.keys(categories).length > 0) {
  lines.push("const C: Record<string, string> = ");
  lines.push(JSON.stringify(categories, null, 0) + ";");
} else {
  lines.push("const C: Record<string, string> = {};");
}

lines.push("");
lines.push(
  "export type TCompactGivenNameEntry = { value: string; category?: string };",
);
lines.push("");
lines.push(
  "let cache: Record<string, Record<string, Record<string, TCompactGivenNameEntry[]>>> | null = null;",
);
lines.push("");
lines.push(
  "export function givenNameIndex(): Record<string, Record<string, Record<string, TCompactGivenNameEntry[]>>> {",
);
lines.push("  if (cache) return cache;");
lines.push("  cache = {};");
lines.push("  for (const g of Object.keys(R)) {");
lines.push("    cache[g] = {};");
lines.push("    for (const r of Object.keys(R[g])) {");
lines.push("      cache[g][r] = {};");
lines.push("      for (const e of Object.keys(R[g][r])) {");
lines.push('        cache[g][r][e] = R[g][r][e].split("|").map(v => {');
lines.push("          const c = C[v];");
lines.push("          return c ? { value: v, category: c } : { value: v };");
lines.push("        });");
lines.push("      }");
lines.push("    }");
lines.push("  }");
lines.push("  return cache;");
lines.push("}");

const output = lines.join("\n") + "\n";

// Stats
const originalSize = 872; // KB
const newSize = Buffer.byteLength(output, "utf8") / 1024;
console.log(`Original: ~${originalSize} KB`);
console.log(`Compact:  ~${Math.round(newSize)} KB`);
console.log(`Reduction: ~${Math.round((1 - newSize / originalSize) * 100)}%`);
console.log(`Categories: ${Object.keys(categories).length} entries`);
console.log(
  `Unique names: ${new Set(Object.values(raw).flatMap((r) => Object.values(r).flatMap((e) => Object.values(e).flatMap((s) => s.split("|"))))).size}`,
);

// Write
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
const __dirname = dirname(fileURLToPath(import.meta.url));
writeFileSync(
  join(__dirname, "../src/data/given-name-compact.ts"),
  output,
  "utf8",
);
console.log("\nWritten to src/data/given-name-compact.ts");
