// AUTO-GENERATED by crawl pipeline -- do not edit manually

export const INDEX_MIDDLE_NAME: Record<string, Record<string, Record<string, string[]>>> = {
  "male": {
    "north": {
      "traditional": ["Văn","Hữu","Đức","Quốc"],
      "modern": ["Minh","Quốc","Gia","Đức"]
    },
    "central": {
      "traditional": ["Văn","Đức","Công","Thanh"],
      "modern": ["Minh","Quốc","Bảo","Thanh"]
    },
    "south": {
      "traditional": ["Văn","Thanh","Hữu","Minh"],
      "modern": ["Minh","Hoàng","Gia","Bảo"]
    }
  },
  "female": {
    "north": {
      "traditional": ["Thị","Ngọc","Diệu"],
      "modern": ["Ngọc","Minh","Khánh"]
    },
    "central": {
      "traditional": ["Thị","Ngọc","Mỹ"],
      "modern": ["Ngọc","Bảo","An"]
    },
    "south": {
      "traditional": ["Thị","Ngọc","Kim"],
      "modern": ["Ngọc","Bảo","Gia"]
    }
  },
  "unisex": {
    "north": {
      "traditional": ["Minh","Thanh"],
      "modern": ["An","Bảo"]
    },
    "central": {
      "traditional": ["Minh","Thanh"],
      "modern": ["An","Bảo"]
    },
    "south": {
      "traditional": ["Minh","Kim"],
      "modern": ["An","Gia"]
    }
  }
};
